apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask1
  template:
    metadata:
      labels:
        app: flask1
    spec:
      containers:
      - name: flask-container
        image: 913524946304.dkr.ecr.us-west-2.amazonaws.com/flask-app-repo:v3
        ports:
        - containerPort: 80
